### ISSUE TITLE
Missing Extra Labels for Loki / Logs Destination

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm-migrator#1]
When Migrating a Config that has some `externalLabels` for `loki` in `externalServies` the Migrated Config does not include these.

Example v1 Config:

```yaml
cluster:
  name: cluster-name

externalServices:
  prometheus:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  loki:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  tempo:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
  pyroscope:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring

kepler:
  enabled: true

metrics:
  kepler:
    enabled: true

opencost:
  opencost:
    exporter:
      defaultClusterId: cluster-name

profiles:
  enabled: true

receivers:
  grafanaCloudMetrics:
    enabled: true

traces:
  enabled: true
```

Output from Migrator;

```yaml
cluster:
  name: cluster-name
destinations:
  - name: metricsService
    type: prometheus
    url: https://my-endpoint.com/api/prom/push
    extraLabels:
      env: testing
      source: k8s-monitoring
    auth:
      type: basic
      username: user
      password: pass
  - name: logsService
    type: loki
    url: https://my-endpoint.com/loki/api/v1/push
    auth:
      type: basic
      username: user
      password: pass
  - name: tracesService
    type: otlp
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
  - name: profilesService
    type: pyroscope
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
clusterMetrics:
  enabled: true
  opencost:
    opencost:
      exporter:
        defaultClusterId: cluster-name
  kepler:
    enabled: true
alloy-metrics:
  enabled: true
clusterEvents:
  enabled: true
alloy-singleton:
  enabled: true
podLogs:
  enabled: true
alloy-logs:
  enabled: true
applicationObservability:
  enabled: true
  receivers: {}
alloy-receiver:
  enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
```
