### ISSUE TITLE
Long Comments (in Relabeling Rule Blocks) are split across Multiple Lines

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm-migrator#2]
If you have a Relabeling rule Bock (for example) and you have a comment in there explaining the rule, and its long, the migrator tool splits the line over multiple lines, the result is that the Config block is now Invalid and causes Alloy to fail to start, an example;

v1 Config;

```yaml
cluster:
  name: cluster-name

externalServices:
  prometheus:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  loki:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  tempo:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
  pyroscope:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring

kepler:
  enabled: true

logs:
  pod_logs:
    extraRelabelingRules: |-
      // Custom Relabeling Rule for the My Custom Demo App Container Logs, to remove the "my-custom-demo-app-" Prefix, so they match the Service Name
      rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        target_label = "service_name"
        replacement = "$1"
        regex = "my-custom-demo-app-(.+)"
      }

metrics:
  kepler:
    enabled: true

opencost:
  opencost:
    exporter:
      defaultClusterId: cluster-name

profiles:
  enabled: true

receivers:
  grafanaCloudMetrics:
    enabled: true

traces:
  enabled: true
```

Output of Migrator;

```yaml
cluster:
  name: cluster-name
destinations:
  - name: metricsService
    type: prometheus
    url: https://my-endpoint.com/api/prom/push
    extraLabels:
      env: testing
      source: k8s-monitoring
    auth:
      type: basic
      username: user
      password: pass
  - name: logsService
    type: loki
    url: https://my-endpoint.com/loki/api/v1/push
    auth:
      type: basic
      username: user
      password: pass
  - name: tracesService
    type: otlp
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
  - name: profilesService
    type: pyroscope
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
clusterMetrics:
  enabled: true
  opencost:
    opencost:
      exporter:
        defaultClusterId: cluster-name
  kepler:
    enabled: true
alloy-metrics:
  enabled: true
clusterEvents:
  enabled: true
alloy-singleton:
  enabled: true
podLogs:
  enabled: true
  extraDiscoveryRules: >-
    // Custom Relabeling Rule for the My Custom Demo App Container Logs, to
    remove the "my-custom-demo-app-" Prefix, so they match the Service Name

    rule {
      source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
      target_label = "service_name"
      replacement = "$1"
      regex = "my-custom-demo-app-(.+)"
    }
alloy-logs:
  enabled: true
applicationObservability:
  enabled: true
  receivers: {}
alloy-receiver:
  enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true

```

The key part is this bit here;

```
  extraDiscoveryRules: >-
    // Custom Relabeling Rule for the My Custom Demo App Container Logs, to
    remove the "my-custom-demo-app-" Prefix, so they match the Service Name
```

Its split the comment across two lines now
