### ISSUE TITLE
Logs `extraConfig` Block is not Migrated

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm-migrator#3]
The Logs Extra Config Settings are not Migrated and dont show in the Migrated Config, an example;

v1 Config;

```yaml
cluster:
  name: cluster-name

externalServices:
  prometheus:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  loki:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  tempo:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
  pyroscope:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring

kepler:
  enabled: true

logs:
  extraConfig: |
    discovery.relabel "postgres_logs" {
      targets = discovery.relabel.pod_logs.output

      rule {
        source_labels = ["namespace"]
        regex = ".*"
        action = "keep"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_database_type"]
        regex = "postgres"
        action = "keep"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label = "instance"
      }
    }

metrics:
  kepler:
    enabled: true

opencost:
  opencost:
    exporter:
      defaultClusterId: cluster-name

profiles:
  enabled: true

receivers:
  grafanaCloudMetrics:
    enabled: true

traces:
  enabled: true
```

Output from Migrator;

```yaml
cluster:
  name: cluster-name
destinations:
  - name: metricsService
    type: prometheus
    url: https://my-endpoint.com/api/prom/push
    extraLabels:
      env: testing
      source: k8s-monitoring
    auth:
      type: basic
      username: user
      password: pass
  - name: logsService
    type: loki
    url: https://my-endpoint.com/loki/api/v1/push
    auth:
      type: basic
      username: user
      password: pass
  - name: tracesService
    type: otlp
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
  - name: profilesService
    type: pyroscope
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
clusterMetrics:
  enabled: true
  opencost:
    opencost:
      exporter:
        defaultClusterId: cluster-name
  kepler:
    enabled: true
alloy-metrics:
  enabled: true
clusterEvents:
  enabled: true
alloy-singleton:
  enabled: true
podLogs:
  enabled: true
alloy-logs:
  enabled: true
applicationObservability:
  enabled: true
  receivers: {}
alloy-receiver:
  enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
```
