### ISSUE TITLE
Annotation Discovery Relabeling Rules are not Migrated

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm-migrator#6]
The Auto Discovery (Annotation Discovery) Relabelling Rules are not Migrated using the Migration Tool;

Example v1 Config;

```yaml
cluster:
  name: cluster-name

externalServices:
  prometheus:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  loki:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  tempo:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
  pyroscope:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring

kepler:
  enabled: true

metrics:
  alloy:
    metricsTuning:
      includeMetrics: [".*"]
      useIntegrationAllowList: false
  autoDiscover:
    extraRelabelingRules: |-
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }
  kepler:
    enabled: true

opencost:
  opencost:
    exporter:
      defaultClusterId: cluster-name

profiles:
  enabled: true

receivers:
  grafanaCloudMetrics:
    enabled: true

traces:
  enabled: true
```

However this is not included in the Output of the Migration Tool;

```yaml
cluster:
  name: cluster-name
destinations:
  - name: metricsService
    type: prometheus
    url: https://my-endpoint.com/api/prom/push
    extraLabels:
      env: testing
      source: k8s-monitoring
    auth:
      type: basic
      username: user
      password: pass
  - name: logsService
    type: loki
    url: https://my-endpoint.com/loki/api/v1/push
    auth:
      type: basic
      username: user
      password: pass
  - name: tracesService
    type: otlp
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
  - name: profilesService
    type: pyroscope
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
clusterMetrics:
  enabled: true
  opencost:
    opencost:
      exporter:
        defaultClusterId: cluster-name
  kepler:
    enabled: true
alloy-metrics:
  enabled: true
clusterEvents:
  enabled: true
alloy-singleton:
  enabled: true
podLogs:
  enabled: true
alloy-logs:
  enabled: true
applicationObservability:
  enabled: true
  receivers: {}
alloy-receiver:
  enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
```
