### ISSUE TITLE
Profiles Configuration is not Migrated

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm-migrator#7]
The Profiling / Profiles Configuration is not migrated by the tool;

Example v1 Config;

```yaml
cluster:
  name: cluster-name

externalServices:
  prometheus:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  loki:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  tempo:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
  pyroscope:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring

kepler:
  enabled: true

metrics:
  kepler:
    enabled: true

opencost:
  opencost:
    exporter:
      defaultClusterId: cluster-name

profiles:
  enabled: true
  ebpf:
    enabled: false
  java:
    enabled: false
  pprof:
    extraRelabelingRules: |
      // Set the `service_name` Label to match the OTEL Service Name Value, for App o11y.
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label = "service_name"
      }

receivers:
  grafanaCloudMetrics:
    enabled: true

traces:
  enabled: true
```

Output of Migrator Tool;

```yaml
cluster:
  name: cluster-name
destinations:
  - name: metricsService
    type: prometheus
    url: https://my-endpoint.com/api/prom/push
    extraLabels:
      env: testing
      source: k8s-monitoring
    auth:
      type: basic
      username: user
      password: pass
  - name: logsService
    type: loki
    url: https://my-endpoint.com/loki/api/v1/push
    auth:
      type: basic
      username: user
      password: pass
  - name: tracesService
    type: otlp
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
  - name: profilesService
    type: pyroscope
    url: https://my-endpoint.com
    auth:
      type: basic
      username: user
      password: pass
clusterMetrics:
  enabled: true
  opencost:
    opencost:
      exporter:
        defaultClusterId: cluster-name
  kepler:
    enabled: true
alloy-metrics:
  enabled: true
clusterEvents:
  enabled: true
alloy-singleton:
  enabled: true
podLogs:
  enabled: true
alloy-logs:
  enabled: true
applicationObservability:
  enabled: true
  receivers: {}
alloy-receiver:
  enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
```
