### ISSUE TITLE
No Error if URL or Username/Password is missing from Config

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm-migrator#8]
If your Values File is missing the Promethues URL, Username or Password (for example if you set it with the HELM Command / Terraform etc), the Migration Tool fails, without an error.

Looking in the Console I can see some Errors logged there;

![Image](https://github.com/user-attachments/assets/16687bc0-605c-462b-9fa0-e2a11a65f6e4)

Example v1 Config;

```yaml
cluster:
  name: cluster-name

externalServices:
  prometheus:
    externalLabels:
      env: testing
      source: k8s-monitoring
  loki:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring
  tempo:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
  pyroscope:
    host: "https://my-endpoint.com"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: testing
      source: k8s-monitoring

kepler:
  enabled: true

metrics:
  kepler:
    enabled: true

opencost:
  opencost:
    exporter:
      defaultClusterId: cluster-name

profiles:
  enabled: true
  ebpf:
    enabled: false
  java:
    enabled: false
  pprof:
    extraRelabelingRules: |
      // Set the `service_name` Label to match the OTEL Service Name Value, for App o11y.
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label = "service_name"
      }

receivers:
  grafanaCloudMetrics:
    enabled: true

traces:
  enabled: true
```

Ideally it should be able to handle this, or return a visible error in the UI.
